### ISSUE TITLE
how to use apscheduler's listener in fastapi?

### ISSUE THREAD

**Issue by findre** [cryptoroo/fastapi-scheduled-ssl-checks#1]
hi, cryptoroo,

1. thanks for your example and sorry for my english, 

2. in my project, I want to use apscheduler's listener,

e.g.
`scheduler.add_listener(whatever_func, any_event)`

but in 'whatever_func', i can't use aiomysql / aioredis / ..... beacuse it isn't an aiosync fun.

do you have any idea to solve it?

**Comment by cryptoroo** [comment]
i don't have much experience yet with aioredis or aiomysql

**async def** check_host_certificate(host="www.google.com"):

the async def might be able to help you out here. 

https://gist.github.com/h1code2/f3bba962a694c126ae320a5d87cd5875 

aio is an async library so you need to make sure you await certain components.

**Comment by findre** [comment]
thanks，i closed it.
